getsentry/gocd-jsonnet

- .github/workflows/build-and-test.yaml
- Makefile
- README.md
- jsonnetfile.json
- package-lock.json
- package.json
- test/testdata/v1.0.0-pipedream-autodeploy.jsonnet
- test/testdata/v1.0.0-pipedream-autodeploy.jsonnet.golden
- test/testdata/v1.0.0-pipedream-no-autodeploy.jsonnet
- test/testdata/v1.0.0-pipedream-no-autodeploy.jsonnet.golden
- test/utils/testdata.js
- test/v1.0.0/pipedream.js
- v1.0.0/gocd-tasks.libsonnet
- v1.0.0/pipedream.libsonnet
This PR largely scaffolds the jsonnet lib files that other services would use.
Some notes about this PR:
1. This creates the pipeline that would start a pipedream run (i.e. trigger to start deployments across all regions)
2. The testing framework is very rough and will be replaced by @bukzor-sentryio's tool when available
> Adding start of gocd jsonnet libraries

- .github/workflows/build-and-test.yaml
- Makefile
- README.md
- jsonnetfile.json
- package-lock.json
- package.json
- test/testdata/v1.0.0-pipedream-autodeploy.jsonnet
- test/testdata/v1.0.0-pipedream-autodeploy.jsonnet.golden
- test/testdata/v1.0.0-pipedream-no-autodeploy.jsonnet
- test/testdata/v1.0.0-pipedream-no-autodeploy.jsonnet.golden
- test/utils/testdata.js
- test/v1.0.0/pipedream.js
- v1.0.0/gocd-tasks.libsonnet
- v1.0.0/pipedream.libsonnet
Loop over a set of names regions, calling the service provided callback function.
> Generate service pipelines

- Makefile
- libs/pipedream.libsonnet
- test/testdata/pipedream/autodeploy.jsonnet_output-files.golden
- test/testdata/pipedream/autodeploy.jsonnet_single-file.golden
- test/testdata/pipedream/minimal-config.jsonnet_output-files.golden
- test/testdata/pipedream/minimal-config.jsonnet_single-file.golden
- test/testdata/pipedream/no-autodeploy.jsonnet_output-files.golden
- test/testdata/pipedream/no-autodeploy.jsonnet_single-file.golden
These regions run in parallel to the primary pipedream
> Add notion of test regions to pipedream

- libs/pipedream.libsonnet
- test/testdata/pipedream/autodeploy.jsonnet_output-files.golden
- test/testdata/pipedream/autodeploy.jsonnet_single-file.golden
- test/testdata/pipedream/no-autodeploy.jsonnet_output-files.golden
- test/testdata/pipedream/no-autodeploy.jsonnet_single-file.golden
since we have no guarantee they will have the same SHAs in their deployment as pipedream
> Do not include test regions in rollback 

- libs/pipedream.libsonnet
- test/pipedream.js
- test/testdata/fixtures/pipedream/exclude-regions-no-autodeploy.jsonnet
- test/testdata/goldens/pipedream/exclude-regions-no-autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/exclude-regions-no-autodeploy.jsonnet_single-file.golden
The primary change here is that I'm using the array of pipelines to figure out what is needed in the rollback instead of using expected names and regions, so this should be a little more future proof.
> Ensure rollback pipelines handle exclude regions

- libs/pipedream.libsonnet
- test/pipedream.js
- test/testdata/goldens/pipedream/autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/autodeploy.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/exclude-regions-no-autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/exclude-regions-no-autodeploy.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/exclude-regions.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/exclude-regions.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/minimal-config.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/minimal-config.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/no-autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/no-autodeploy.jsonnet_single-file.golden
Example of problem run: https://deploy.getsentry.net/go/materials/value_stream_map/b30fe60e4e3a0a339cfcab9e5511f2efe32200d1a4958d6d6d96e6d75e00a66f/e55578b4e3c683eede9d8ce10dddd2b198a1a098
> Add final stage to end of pipelines

- libs/bash/unpause-and-unlock-pipelines.sh
- libs/bash/unpause-pipelines.sh
- libs/pipedream.libsonnet
- test/pipedream.js
- test/testdata/goldens/pipedream/autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/autodeploy.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/exclude-regions-no-autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/exclude-regions-no-autodeploy.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/exclude-regions.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/exclude-regions.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/no-autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/no-autodeploy.jsonnet_single-file.golden
Depends on https://github.com/getsentry/devinfra-deployment-service/pull/478
> Adding unpause pipelines script to rollbacks

- .gitignore
- libs/getsentry.libsonnet
- libs/pipedream.libsonnet
- test/testdata/fixtures/getsentry/regions.jsonnet
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
> export regions

- README.md
- package.json
- test/getsentry.js
- test/gocd-pipelines.js
- test/gocd-stages.js
- test/gocd-tasks.js
- test/pipedream.js
- test/utils/testdata.js
supersafe: only whitespace was changed
> chore: prettier

- .eslintrc.json
- .github/workflows/build-and-test.yaml
- .prettierrc.json
- package-lock.json
- package.json
- test/getsentry.js
- test/gocd-pipelines.js
- test/gocd-stages.js
- test/gocd-tasks.js
- test/pipedream.js
- test/utils/testdata.js
Building off of #60, adding prettier and eslint to the ci so we can enforce the formatting.
> Adding linting to ci

- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
Move `de` deploys to the test_regions list while we're rolling things out, this will help prevent failures from causing issues in the rest of the pipeline.
> Move `de` deploys to test_regions while validating

- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
Until we figure out what is causing it to fail.
> Removing de region temporarily

- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
Adding the de region back in as a test region so that it doesn't block deploys if it breaks.
> Adding de region back in as a test-region

- README.md
- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
Now that the DE region is live (with customers on it), we should move it's deployments to be inline with our other production regions. This change will put DE deployments after S4S and before US.
> Update prod_regions to include de

- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
Added `customer-7` and test data.
> added customer-7 and test data

- README.md
- libs/bash/pause-pipelines.sh
Adding the ability to customize the pause message for rollbacks using environment variables.
> Adding ability to dictate pause message using env vars

- README.md
- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
Now that customer-7 has been used as a test region for some time and has shown to be reliable, it is a good time to move it to a proper production region.
> Moving customer-7 to prod

- README.md
Preparing to cut a new release, updating Readme.
> chore: bump version for new release

- libs/getsentry.libsonnet
- test/pipedream.js
- test/testdata/fixtures/pipedream/exclude-regions-no-autodeploy.jsonnet
- test/testdata/fixtures/pipedream/exclude-regions.jsonnet
- test/testdata/goldens/getsentry/regions.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/autodeploy.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/minimal-config.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/minimal-config.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/no-autodeploy.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/no-autodeploy.jsonnet_single-file.golden
- test/testdata/goldens/pipedream/rollback-override-final-stage.jsonnet_output-files.golden
- test/testdata/goldens/pipedream/rollback-override-final-stage.jsonnet_single-file.golden
> remove: Customer-3 removal

- README.md
Bumping version to 2.15.0 in preparation for cutting a new release
> Bumping version
